worker_processes 1;
error_log /var/log/nginx/rtmp-error.log;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
            allow publish 127.0.0.1;
            deny  publish all;
            allow play   127.0.0.1;
            deny  play   all;
        }
    }
}
